//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabaMaker2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<double> price { get; set; }
        public string task_link { get; set; }
        public string solutio_link { get; set; }
        public Nullable<bool> paid { get; set; }
        public Nullable<int> user_id { get; set; }
    }
}
